# ============================================================
# ADD THIS BLOCK AT THE END OF YOUR ANALYSIS SCRIPT
# It writes output/tables/main_result.tex automatically
# so paper.tex never contains hand-typed numbers.
# ============================================================

write_latex_table <- function(result, outpath) {

  paper_ate <- c(8187, 8871, 9247, 9110, 9038, 9166, 9215)
  paper_adj <- c(1558, 1418, 1328, 1328, 1355, 1310, 1312)
  paper_se  <- c(1298, 1358, 1295, 1314, 1322, 1299, 1294)

  fmt_row <- function(vals) paste(vals, collapse = " & ")

  rep_ate <- result["ATE (5-fold)",  ]
  rep_adj <- result["[Adjusted SE]", ]
  rep_se  <- result["(Median SE)",   ]

  lines <- c(
    "% This file is auto-generated by code/analysis.R — do not edit by hand.",
    "\\begin{table}[h]",
    "\\centering",
    "\\caption{Replication of Table~2, Panel~B (5-Fold): Estimated ATE of 401(k)",
    "         Eligibility on Net Financial Assets (Partially Linear DML).}",
    "\\label{tab:main}",
    "\\begin{tabular}{lccccccc}",
    "\\toprule",
    " & Lasso & Reg.\\ Tree & Forest & Boosting & Neural Net & Ensemble & Best \\\\",
    "\\midrule",
    "\\multicolumn{8}{l}{\\textit{Panel A: Paper targets (Chernozhukov et al., 2018)}} \\\\",
    paste("ATE       &", fmt_row(paper_ate), "\\\\"),
    paste("          &", fmt_row(paste0("[", paper_adj, "]")), "\\\\"),
    paste("          &", fmt_row(paste0("(", paper_se,  ")")), "\\\\"),
    "\\midrule",
    "\\multicolumn{8}{l}{\\textit{Panel B: This replication}} \\\\",
    paste("ATE       &", fmt_row(rep_ate), "\\\\"),
    paste("          &", fmt_row(paste0("[", rep_adj, "]")), "\\\\"),
    paste("          &", fmt_row(paste0("(", rep_se,  ")")), "\\\\"),
    "\\bottomrule",
    "\\end{tabular}",
    "\\end{table}"
  )

  writeLines(lines, outpath)
  cat("LaTeX table written to:", outpath, "\n")
}

# Call it — adjust path to match your directory structure
write_latex_table(
  result  = result,   # the 3-row matrix produced earlier in the script
  outpath = "output/tables/main_result.tex"
)

# Console summary for the grader
cat("\n==========================================\n")
cat(" Replication Result vs. Paper\n")
cat("==========================================\n")
methods_print <- c("Lasso", "Forest", "Boosting", "Ensemble")
paper_ate     <- c(8187,    9247,     9110,        9166)
for (i in seq_along(methods_print)) {
  m    <- methods_print[i]
  rep  <- round(result["ATE (5-fold)", m], 0)
  diff <- rep - paper_ate[i]
  cat(sprintf("  %-12s  paper: %5d   ours: %5d   diff: %+d\n",
              m, paper_ate[i], rep, diff))
}
cat("==========================================\n")
